project/app/urls.py
from django.urls import path
from .views import IndexView, ProcessingView

app_name = 'app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('api/processing/', ProcessingView.as_view(), name='processing'),
]

project/system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/app/models.py
import os

from django.db import models


class FileModel(models.Model):

    class StatusesChoice(models.TextChoices):
        LOAD = 'LOAD', 'Загружено'
        PROCESSING = 'PROCESSING', 'Обрабатывается'
        READY = 'READY', 'Обработано'

    status = models.CharField(
        max_length=127, choices=StatusesChoice.choices,
        default=StatusesChoice.LOAD)
    file_obj = models.FileField(
        verbose_name='Файл', blank=False)
    created_at = models.DateTimeField(
        verbose_name='Дата загрузки', auto_now_add=True)
    finished_at = models.DateTimeField(
        verbose_name='Дата завершения', blank=True, null=True)
    result = models.TextField(
        verbose_name='Результат', blank=True)
    
    def __str__(self) -> str:
        return f'Файл {self.pk} {self.created_at}'

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
        ordering = ('-created_at',)

    def get_info(self):
        name, extension = os.path.splitext(self.file_obj.name)
        return name, extension[1:]

    def get_size(self):
        size = os.path.getsize(self.file_obj.path)
        if size < 512000:
            size = size / 1024.0
            ext = 'Кб'
        elif size < 4194304000:
            size = size / 1048576.0
            ext = 'Мб'
        else:
            size = size / 1073741824.0
            ext = 'Гб'
        return f'{size:.2f} {ext}'

project/app/forms.py
import os
from django import forms
from .models import FileModel


class FileModelForm(forms.ModelForm):
    ALLOWED_TYPES = ['xlsx']

    file_error_messages = {'required': 'Загрузите файл'}

    file_obj = forms.FileField(error_messages=file_error_messages)

    class Meta:
        model = FileModel
        fields = ('file_obj',)

    def clean_file_obj(self):
        file_obj = self.cleaned_data.get('file_obj', None)
        if not file_obj:
            raise forms.ValidationError('Файл не загружен')
   
        extension = os.path.splitext(file_obj.name)[1][1:].lower()
        if extension in self.ALLOWED_TYPES:
            return file_obj
        else:
            raise forms.ValidationError('Тип файла не разрешен')
 

project/app/views.py
from django.views.generic import TemplateView, CreateView
from django.http.response import JsonResponse
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.db import transaction

from .forms import FileModelForm
from .models import FileModel


class IndexView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'files_qs': FileModel.objects.all()})
        return context


class AjaxableResponseMixin:
    http_method_names = ['post']

    def dispatch(self, request, *args, **kwargs):
        token = request.POST.get('token', None)
        if token and token == '5806d76c-2728-4dc1-a3e7-e79f374b6b95':
            return super().dispatch(request, *args, **kwargs)
        return HttpResponse(status=403)

    def form_invalid(self, form):
        return JsonResponse({
            'errors': form.errors,
            'success': False
        })

    def form_valid(self, form):
        data = {'success': True}
        data.update(self.extra_data())
        return JsonResponse(data)

    def extra_data(self):
        return {}


class ProcessingView(AjaxableResponseMixin, CreateView):
    table_template = 'table.html'
    form_class = FileModelForm

    @transaction.atomic()
    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)
    
    def extra_data(self):
        return {
            'message': 'Файл отправлен на обработку',
            'template': render_to_string(
                self.table_template, {
                    'files_qs': FileModel.objects.all()
                }
            )
        }

project/app/templates/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="index-wrapper">
            <div class="block">
                <p class="block-title">Загрузка файла</p>
                <form id="mainForm" action="{% url 'app:processing' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="token" value="5806d76c-2728-4dc1-a3e7-e79f374b6b95">
                    <input type="file" name="file_obj">
                    <button type="submit">Отправить</button>
                </form>
                <div id="errors-container"></div>
                <div id="ok-container"></div>
            </div>
            <div class="block">
                <p class="block-title">История загрузок</p>
                <div id="table-container">
                    {% include 'table.html' %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

project/app/templates/table.html
{% if files_qs %}
    <div class="table">
        <div class="cell">ID</div>
        <div class="cell">Файл</div>
        <div class="cell">Дата загрузки</div>
        <div class="cell">Дата завершения</div>
        <div class="cell">Статус</div>
        <div class="cell">Результат</div>
        {% for file in files_qs %}
            <div class="cell">{{ file.pk }}</div>
            <div class="cell"><a href="{{ file.file_ob.url }}">{{ file.file_obj.name }}<br>({{ file.get_size }})</a></div>
            <div class="cell">{{ file.created_at|date:"d.m.Y H:i:s" }}</div>
            <div class="cell">{{ file.finished_at|date:"d.m.Y H:i:s" }}</div>
            <div class="cell">{{ file.get_status_display }}</div>
            <div class="cell">{{ file.result }}</div>
        {% endfor %}
    </div>
{% else %}
    <p>История пуста</p>
{% endif %}

project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TEST CASE</title>
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
</head>
<body>
    <main>
        <header>

        </header>
        <section>
            {% block content %}
            {% endblock content %}
        </section>
    </main>
    <footer>
        <script src="{% static '/js/index.bundle.js' %}"></script>
    </footer>
</body>
</html>